[[pages]]
path = "Home.py"
name = "InÃ­cio"
icon = "ğŸ "

[[pages]]
path = "Entrada_de_Dados.py"
name = "Entrada de GrÃ£os"
icon = "â¬†ï¸"

[[pages]]
path = "Saida_de_Dados.py"
name = "SaÃ­da de GrÃ£os"
icon = "â¬‡ï¸"

[[pages]]
path = "Relatorios.py"
name = "RelatÃ³rios"
icon = "ğŸ“Š"
